---
# tasks file for tendrl-node

- name: Install tendrl-selinux
  yum:
    name=tendrl-selinux
    state=latest

- name: Install tendrl-collectd-selinux
  yum:
    name=tendrl-collectd-selinux
    state=latest

- include_tasks: rsyslog.yml
- include_tasks: tendrl-node-agent.yml
- include_tasks: firewalld.yml
  when: configure_firewalld_for_tendrl == True
