language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  # - sudo apt-get install -y rpmlint
install:
  - pip install yamllint
  - pip install ansible-review
script:
  - yamllint .
  - git ls-files | grep '^[^\.].*\.yml$' | xargs ansible-review
  # - rpmlint tendrl-ansible.spec
