language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  # - sudo apt-get install -y rpmlint
install:
  - pip install yamllint
  - pip install ansible-lint
script:
  - yamllint .
  - ansible-lint prechecks.yml
  # - rpmlint tendrl-ansible.spec
