---

- name: Install tendrl-monitoring-integration
  yum:
    name=tendrl-monitoring-integration
    state=latest

- name: Initialize graphite-db
  command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
  register: graphite_syncdb

- debug: msg={{ graphite_syncdb.stdout }}

- name: Allow apache to access graphite.db file
  file:
    path: /var/lib/graphite-web/graphite.db
    owner: apache
    group: apache

- name: Start carbon-cache service
  service:
    name=carbon-cache
    state=started

- name: Enable carbon-cache service
  service:
    name=carbon-cache
    enabled=yes

- name: Enable grafana-server service
  service:
    name=grafana-server
    enabled=yes
    daemon_reload=yes

- name: Start grafana-server service
  service:
    name=grafana-server
    state=started

- name: Configure tendrl-monitoring-integration
  lineinfile:
    dest=/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: '^datasource_host:.*'
      line: "datasource_host: {{ graphite_ip_address }}"

- name: Start tendrl-monitoring-integration service
  service:
    name=tendrl-monitoring-integration
    state=started

- name: Enable tendrl-monitoring-integration service
  service:
    name=tendrl-monitoring-integration
    enabled=yes
